---
title: "ALD_FDA_Dissertation"
author: "Suryadyuti Baral"
date: "`r Sys.Date()`"
output: html_document
---

### GF

```{r}
library(data.table)
ald_dat <- fread("C:/Users/sonnet/Box/FDA/Emilio_dissertation/Dissertation_Selection.csv", na.strings = ".")

# Setup
response_vars <- c("GF1", "GF2")
time_vars <- c("age1", "age2")

# Remove rows where any age < 5 and >27
valid_indices <- apply(ald_dat[, ..time_vars], 1, function(row) all(is.na(row) | row >= 5 & row <= 27))
ald_dat <- ald_dat[valid_indices]

# Construct Lt and Ly using lapply (with -500 shift)
tmp <- lapply(1:nrow(ald_dat), function(i) {
  y <- unlist(ald_dat[i, ..response_vars])
  t <- unlist(ald_dat[i, ..time_vars])
  keep <- !(is.na(y) | is.na(t))
  list(Ly = y[keep] - 500, Lt = t[keep])
})
Ly <- lapply(tmp, `[[`, "Ly")
Lt <- lapply(tmp, `[[`, "Lt")

# Prepare for modeling
unique_ages <- sort(unique(unlist(Lt)))
first_fr_scores <- na.omit(sapply(Ly, function(y) if (length(y)) y[1] else NA))
sort(unique_ages)
```

```{r}
# Load model code
source("C:/Users/sonnet/Box/FDA/Dynamic-Modeling-of-Functional-Snippets-main/code/ldm.R")
source("C:/Users/sonnet/Box/FDA/Dynamic-Modeling-of-Functional-Snippets-main/code/kerFctn.R")

# Fit model with regular time grid
set.seed(1)
age <- 5:27
M <- length(first_fr_scores)
acd_fda <- ldm(Ly, Lt, z0 = c(-59, 5), age, optns = list(M = M))
n_subj <- length(Ly)

df <- data.frame(
  Age = c(unlist(Lt), rep(age, M)),
  Value = c(unlist(Ly), as.vector(t(acd_fda$path))),
  id = rep(1:(n_subj + M), c(sapply(Lt, length), rep(length(age), M))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

library(ggplot2)
ggplot(data = df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Observed snippets"), 
            aes(color = group), linewidth = 0.4) +
  geom_line(data = subset(df, group == "Estimated growth curves"), 
            aes(color = group), alpha = 0.2, linewidth = 0.4) +
  scale_color_manual(values = c("#B47846", "steelblue")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw() +
  theme(text = element_text(size = 16))

# Save model
saveRDS(acd_fda, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GF_dissertation_ALD_1_sim_curves.rds")
acd_fda <- readRDS(file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GF_dissertation_ALD_1_sim_curves.rds")
```


```{r}
# Fit with irregular design using previous bandwidths
z0_fr <- cbind(sample(seq(-59, -34, length.out = M*100), replace = TRUE), age[1])
acd_fda_2 <- ldm(Ly, Lt, z0_fr, age, optns = list(M = M*100, bw1 = acd_fda$optns$bw1, 
                                                  bw2 = acd_fda$optns$bw2, regular = FALSE))
saveRDS(acd_fda_2, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GF_dissertation_ALD_100_sim_curves.rds")

# Plotting
n_subj <- length(Ly)
df <- data.frame(
  Age = c(unlist(Lt), rep(age, M*100)),
  Value = c(unlist(Ly), as.vector(t(acd_fda_2$path))),
  id = rep(1:(n_subj + M*100), c(sapply(Lt, length), rep(length(age), M*100))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M*100 * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

ggplot(df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Estimated growth curves"),
            aes(color = group), alpha = 0.1, linewidth = 0.4) +
  geom_line(data = subset(df, group == "Observed snippets"),
            aes(color = group), linewidth = 0.4) +
  scale_color_manual(values = c("steelblue", "#B47846")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw(base_size = 16)
```


```{r}
library(fdapace)
library(fda)

curve_matrix <- as.matrix(acd_fda_2$path)
age_grid <- 5:27
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd<-FPCA(Ly, Lt_age)
plot(fpca_acd)

curve_matrix <- as.matrix(acd_fda$path)
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd1<-FPCA(Ly, Lt_age)
plot(fpca_acd1)
```


### GAK
```{r}
ald_dat <- fread("C:/Users/sonnet/Box/FDA/Emilio_dissertation/Dissertation_Selection.csv", na.strings = ".")
response_vars <- c("GAK1", "GAK2")

# Remove rows where any age < 5 and >27
valid_indices <- apply(ald_dat[, ..time_vars], 1, function(row) all(is.na(row) | row >= 5 & row <= 27))
ald_dat <- ald_dat[valid_indices]

# Construct Lt and Ly using lapply (with -500 shift)
tmp <- lapply(1:nrow(ald_dat), function(i) {
  y <- unlist(ald_dat[i, ..response_vars])
  t <- unlist(ald_dat[i, ..time_vars])
  keep <- !(is.na(y) | is.na(t))
  list(Ly = y[keep] - 500, Lt = t[keep])
})
Ly <- lapply(tmp, `[[`, "Ly")
Lt <- lapply(tmp, `[[`, "Lt")

# Prepare for modeling
unique_ages <- sort(unique(unlist(Lt)))
first_fr_scores <- na.omit(sapply(Ly, function(y) if (length(y)) y[1] else NA))
sort(unique_ages)
```

```{r}
# Fit model with regular time grid
set.seed(1)
age <- 5:27
M <- length(first_fr_scores)
acd_fda <- ldm(Ly, Lt, z0 = c(-45, 5), age, optns = list(M = M))
n_subj <- length(Ly)

df <- data.frame(
  Age = c(unlist(Lt), rep(age, M)),
  Value = c(unlist(Ly), as.vector(t(acd_fda$path))),
  id = rep(1:(n_subj + M), c(sapply(Lt, length), rep(length(age), M))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

library(ggplot2)
ggplot(data = df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Observed snippets"), 
            aes(color = group), linewidth = 0.4) +
  geom_line(data = subset(df, group == "Estimated growth curves"), 
            aes(color = group), alpha = 0.2, linewidth = 0.4) +
  scale_color_manual(values = c("#B47846", "steelblue")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw() +
  theme(text = element_text(size = 16))
# Save model
saveRDS(acd_fda, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GAK_dissertation_ALD_1_sim_curves.rds")
```


```{r}
# Fit with irregular design using previous bandwidths
z0_fr <- cbind(sample(seq(-69, -31, length.out = M*100), replace = TRUE), age[1])
acd_fda_2 <- ldm(Ly, Lt, z0_fr, age, optns = list(M = M*100, bw1 = acd_fda$optns$bw1, 
                                                  bw2 = acd_fda$optns$bw2, regular = FALSE))
saveRDS(acd_fda_2, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GAK_dissertation_ALD_100_sim_curves.rds")

# Plotting
n_subj <- length(Ly)
df <- data.frame(
  Age = c(unlist(Lt), rep(age, M*100)),
  Value = c(unlist(Ly), as.vector(t(acd_fda_2$path))),
  id = rep(1:(n_subj + M*100), c(sapply(Lt, length), rep(length(age), M*100))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M*100 * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

ggplot(df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Estimated growth curves"),
            aes(color = group), alpha = 0.1, linewidth = 0.4) +
  geom_line(data = subset(df, group == "Observed snippets"),
            aes(color = group), linewidth = 0.4) +
  scale_color_manual(values = c("steelblue", "#B47846")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw(base_size = 16)
```

```{r}
library(fdapace)
library(fda)

curve_matrix <- as.matrix(acd_fda_2$path)
age_grid <- 5:27
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd<-FPCA(Ly, Lt_age)
plot(fpca_acd)

curve_matrix <- as.matrix(acd_fda$path)
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd1<-FPCA(Ly, Lt_age)
plot(fpca_acd1)
```


### GC
```{r}
ald_dat <- fread("C:/Users/sonnet/Box/FDA/Emilio_dissertation/Dissertation_Selection.csv", na.strings = ".")
response_vars <- c("GC1", "GC2")

# Remove rows where any age < 5 and >27
valid_indices <- apply(ald_dat[, ..time_vars], 1, function(row) all(is.na(row) | row >= 5 & row <= 27))
ald_dat <- ald_dat[valid_indices]

# Construct Lt and Ly using lapply (with -500 shift)
tmp <- lapply(1:nrow(ald_dat), function(i) {
  y <- unlist(ald_dat[i, ..response_vars])
  t <- unlist(ald_dat[i, ..time_vars])
  keep <- !(is.na(y) | is.na(t))
  list(Ly = y[keep] - 500, Lt = t[keep])
})
Ly <- lapply(tmp, `[[`, "Ly")
Lt <- lapply(tmp, `[[`, "Lt")

# Prepare for modeling
unique_ages <- sort(unique(unlist(Lt)))
first_fr_scores <- na.omit(sapply(Ly, function(y) if (length(y)) y[1] else NA))
sort(unique_ages)
```

```{r}
set.seed(1)
age <- 5:27
M <- length(first_fr_scores)
acd_fda <- ldm(Ly, Lt, z0 = c(-50, 5), age, optns = list(M = M))
n_subj <- length(Ly)

df <- data.frame(
  Age = c(unlist(Lt), rep(age, M)),
  Value = c(unlist(Ly), as.vector(t(acd_fda$path))),
  id = rep(1:(n_subj + M), c(sapply(Lt, length), rep(length(age), M))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

library(ggplot2)
ggplot(data = df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Observed snippets"), 
            aes(color = group), linewidth = 0.4) +
  geom_line(data = subset(df, group == "Estimated growth curves"), 
            aes(color = group), alpha = 0.2, linewidth = 0.4) +
  scale_color_manual(values = c("#B47846", "steelblue")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw() +
  theme(text = element_text(size = 16))
# Save model
saveRDS(acd_fda, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GC_dissertation_ALD_1_sim_curves.rds")
acd_fda <- readRDS(file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GC_dissertation_ALD_1_sim_curves.rds")
```


```{r}
# Fit with irregular design using previous bandwidths
z0_fr <- cbind(sample(seq(-86, -36, length.out = M*100), replace = TRUE), age[1])
acd_fda_2 <- ldm(Ly, Lt, z0_fr, age, optns = list(M = M*100, bw1 = acd_fda$optns$bw1, 
                                                  bw2 = acd_fda$optns$bw2, regular = FALSE))
saveRDS(acd_fda_2, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GC_dissertation_ALD_100_sim_curves.rds")
acd_fda_2 <- readRDS(file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GC_dissertation_ALD_100_sim_curves.rds")

# Plotting
n_subj <- length(Ly)
df <- data.frame(
  Age = c(unlist(Lt), rep(age, M*100)),
  Value = c(unlist(Ly), as.vector(t(acd_fda_2$path))),
  id = rep(1:(n_subj + M*100), c(sapply(Lt, length), rep(length(age), M*100))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M*100 * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

ggplot(df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Estimated growth curves"),
            aes(color = group), alpha = 0.1, linewidth = 0.4) +
  geom_line(data = subset(df, group == "Observed snippets"),
            aes(color = group), linewidth = 0.4) +
  scale_color_manual(values = c("steelblue", "#B47846")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw(base_size = 16)
```

```{r}
library(fdapace)
library(fda)

curve_matrix <- as.matrix(acd_fda_2$path)
age_grid <- 5:27
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd<-FPCA(Ly, Lt_age, list(useBinnedData = "OFF"))
plot(fpca_acd)

curve_matrix <- as.matrix(acd_fda$path)
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd1<-FPCA(Ly, Lt_age, list(useBinnedData = "OFF"))
plot(fpca_acd1)
```


### GQ
```{r}
ald_dat <- fread("C:/Users/sonnet/Box/FDA/Emilio_dissertation/Dissertation_Selection.csv", na.strings = ".")
response_vars <- c("GQ1", "GQ2")

# Remove rows where any age < 5 and >27
valid_indices <- apply(ald_dat[, ..time_vars], 1, function(row) all(is.na(row) | row >= 5 & row <= 27))
ald_dat <- ald_dat[valid_indices]

# Construct Lt and Ly using lapply (with -500 shift)
tmp <- lapply(1:nrow(ald_dat), function(i) {
  y <- unlist(ald_dat[i, ..response_vars])
  t <- unlist(ald_dat[i, ..time_vars])
  keep <- !(is.na(y) | is.na(t))
  list(Ly = y[keep] - 500, Lt = t[keep])
})
Ly <- lapply(tmp, `[[`, "Ly")
Lt <- lapply(tmp, `[[`, "Lt")

# Prepare for modeling
unique_ages <- sort(unique(unlist(Lt)))
first_fr_scores <- na.omit(sapply(Ly, function(y) if (length(y)) y[1] else NA))
sort(unique_ages)
```

```{r}
# Fit model with regular time grid
set.seed(1)
age <- 5:27
M <- length(first_fr_scores)
acd_fda <- ldm(Ly, Lt, z0 = c(-50, 5), age, optns = list(M = M))
n_subj <- length(Ly)

df <- data.frame(
  Age = c(unlist(Lt), rep(age, M)),
  Value = c(unlist(Ly), as.vector(t(acd_fda$path))),
  id = rep(1:(n_subj + M), c(sapply(Lt, length), rep(length(age), M))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

library(ggplot2)
ggplot(data = df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Observed snippets"), 
            aes(color = group), linewidth = 0.4) +
  geom_line(data = subset(df, group == "Estimated growth curves"), 
            aes(color = group), alpha = 0.2, linewidth = 0.4) +
  scale_color_manual(values = c("#B47846", "steelblue")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw() +
  theme(text = element_text(size = 16))

# Save model
saveRDS(acd_fda, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GQ_dissertation_ALD_1_sim_curves.rds")
```


```{r}
# Fit with irregular design using previous bandwidths
z0_fr <- cbind(sample(seq(-80, -50, length.out = M*100), replace = TRUE), age[1])
acd_fda_2 <- ldm(Ly, Lt, z0_fr, age, optns = list(M = M*100, bw1 = acd_fda$optns$bw1, 
                                                  bw2 = acd_fda$optns$bw2, regular = FALSE))
saveRDS(acd_fda_2, file = "C:/Users/sonnet/Box/FDA/Emilio_dissertation/GQ_dissertation_ALD_100_sim_curves.rds")

# Plotting
n_subj <- length(Ly)
df <- data.frame(
  Age = c(unlist(Lt), rep(age, M*100)),
  Value = c(unlist(Ly), as.vector(t(acd_fda_2$path))),
  id = rep(1:(n_subj + M*100), c(sapply(Lt, length), rep(length(age), M*100))),
  group = factor(rep(c("Observed snippets", "Estimated growth curves"),
                     c(sum(sapply(Lt, length)), M*100 * length(age))),
                 levels = c("Observed snippets", "Estimated growth curves"))
)

ggplot(df, aes(x = Age, y = Value, group = id)) +
  geom_line(data = subset(df, group == "Estimated growth curves"),
            aes(color = group), alpha = 0.1, linewidth = 0.4) +
  geom_line(data = subset(df, group == "Observed snippets"),
            aes(color = group), linewidth = 0.4) +
  scale_color_manual(values = c("steelblue", "#B47846")) +
  labs(x = "Age", y = "Functional Value", color = "Group") +
  theme_bw(base_size = 16)
```

```{r}
library(fdapace)
library(fda)

curve_matrix <- as.matrix(acd_fda_2$path)
age_grid <- 5:27
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd<-FPCA(Ly, Lt_age)
plot(fpca_acd)

curve_matrix <- as.matrix(acd_fda$path)
Lt_age <- replicate(nrow(curve_matrix), age_grid, simplify = FALSE)
Ly <- split(curve_matrix, row(curve_matrix))
fpca_acd1<-FPCA(Ly, Lt_age)
plot(fpca_acd1)
```
